### ISSUE TITLE
Datetimepicker styles broken when using Angular Material v15 with MDC components

### ISSUE THREAD

**Issue by json-derulo** [h2qutc/angular-material-components#318]
I'm using Angular Material v15 with MDC components (not legacy), and the datetimepicker button styles look broken:

<img width="314" alt="image" src="https://user-images.githubusercontent.com/18580672/220952019-e8f4c1c1-6131-4e94-bee3-06f6ae6fb591.png">

To reproduce:
1. Create a new Angular project with `ng new`
2. Add Angular Material with `ng add`
3. Install and configure Datetimepicker

I can also provide a repository for reproduction if needed.

The reason for missing styles is that the Angular Material legacy modules are imported, i.e.:

https://github.com/h2qutc/angular-material-components/blob/f3b6367c39ac6f06c9b8630bf323f37d7b4f6873/projects/datetime-picker/src/lib/datetime-picker.module.ts#L5

For applications which use legacy components this is fine, but it breaks applications which already use MDC components.

**Comment by json-derulo** [comment]
I fixed it temporarily by [creating a custom Angular Material theme](https://material.angular.io/guide/theming#custom-themes-with-sass) and including the legacy themes that are missing:

```
@include mat.legacy-button-theme($app-theme);
```

It seems to work, but this is just a workaround, there should be a better solution.

**Comment by AleksaNortal** [comment]
I am using ngx-mat-timepicker, version 9, and icons are broken with angular material 15. Because this syntax is used:
`<mat-icon role="img" class="mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color" aria-hidden="true" data-mat-icon-type="font">home</mat-icon>`
While angular material 15 has different syntax:
`<mat-icon aria-hidden="false" aria-label="Example home icon" fontIcon="home"></mat-icon>`

**Comment by h2qutc** [comment]
Hi all, if you use the Angular Material MDC components, please use the version v15.0.0 instead of version v9.0.0 (supporting legacy components) (https://www.npmjs.com/package/@angular-material-components/datetime-picker)
